version: 2

jobs:
  0-build:
    docker: [{image: "centos:7"}]
    working_directory: ~/workspace
    steps:
    - run:
        name: Creating dummy artifacts
        command: |
          mkdir dist
          echo "Hello, world!" > dist/artifact-1;
    - store_artifacts:
        path: ~/workspace/dist
    - persist_to_workspace:
        root: ~/workspace
        paths:
        - dist
  1-test:
    machine: true
    steps:
    - checkout
    - attach_workspace:
        at: ~/workspace
    - run: |
        if [[ `cat ~/workspace/dist/artifact-1` == "Hello, world!" ]]; then
          echo "It worked!";
        else
          echo "Nope!"; exit 1
        fi
    - run:
        name: Install Docker Compose
        command: |
          set -x
          #sudo apt update
          #sudo apt install -y curl
          curl -L https://github.com/docker/compose/releases/download/1.17.1/docker-compose-`uname -s`-`uname -m` | sudo tee /usr/local/bin/docker-compose > /dev/null
          sudo chmod +x /usr/local/bin/docker-compose
    - run:
        name: Execute the tests
        command: |
          docker-compose -f docker-compose-circle-ci.yml up --abort-on-container-exit


workflows:
  version: 2
  pipeline:
    jobs:
    - 0-build
    - 1-test:
        requires: [0-build]
