version: 2

jobs:
  0-doc:
    docker: [{image: "python:2.7"}]
    working_directory: ~/temboard-agent
    steps:
    - checkout
    - run:
        name: Build documentation with Sphinx
        command: |
          pip install --upgrade -r doc/requirements-doc.txt
          python setup.py --long-description | rst2html.py --verbose --halt=warning > README.html
          make -C doc/ clean html
    - store_artifacts:
        path: README.html
        destination: build/README.html

  0-rpm:
    docker: [{image: "centos:7"}]
    working_directory: ~/workspace
    steps:
    - run: yum install -y git ssh
    - checkout
    - run: ./rpm/build.sh
    - store_artifacts:
        path: ~/workspace/dist/
    - persist_to_workspace:
        root: ~/workspace
        paths:
        - dist

  0-unit:
    docker:
      - image: python:2.7
        environment:
          TERM: linux
          TERMINFO: /etc/terminfo
    working_directory: /home/ubuntu/temboard-agent
    steps:
      - checkout
      - restore_cache:
          keys:
            - temboard-agent-{{ .Branch }}
            - temboard-agent-master
      - run:
          name: Python lint and tests
          command: |
            set -x
            pip install --upgrade --requirement requirement-ci.txt --editable .
            git diff --check $(git merge-base origin/master $CIRCLE_SHA1)..$CIRCLE_SHA1
            flake8 temboard-agent/
            pytest test/unit/
            codecov
      - save_cache:
          key: temboard-agent-{{ .Branch }}
          paths:
            - "~/.cache/pip/"

  1-func:
    machine: true
    steps:
    - checkout
    - attach_workspace:
        at: /tmp/workspace
    - run:
        name: Install Docker Compose
        command: |
          set -x
          #sudo apt update
          #sudo apt install -y curl
          curl -L https://github.com/docker/compose/releases/download/1.17.1/docker-compose-`uname -s`-`uname -m` | sudo tee /usr/local/bin/docker-compose > /dev/null
          sudo chmod +x /usr/local/bin/docker-compose
    - run:
        name: Execute the tests
        command: |
          docker-compose -f test/legacy/docker-compose.yml up --abort-on-container-exit


workflows:
  version: 2
  pipeline:
    jobs:
    - 0-doc
    - 0-rpm
    - 0-unit
    - 1-func:
        requires: [0-rpm]
