version: '2'

services:
  centos7: &centos
    image: dalibo/labs-sdk:centos7
    environment:
    - VERSION
    volumes:
    - ../../:/workspace
    command: /workspace/packaging/rpm/build.sh

  centos8:
    <<: *centos
    image: dalibo/labs-sdk:centos8
