version: '2'

services:
  buster: &mkdeb
    image: dalibo/buildpack-pkg:buster
    environment:
      # See dch(1)
      DEBFULLNAME: ${DEBFULLNAME}
      DEBEMAIL: ${DEBEMAIL}
    volumes:
    - ../..:/workspace
    - ../../dist/:/dist
    command: /workspace/packaging/deb/mkdeb.sh

  stretch:
    <<: *mkdeb
    image: dalibo/buildpack-pkg:stretch
